# Generated by Django 3.0.6 on 2020-06-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=70)),
                ('EmailAddress', models.CharField(max_length=200)),
                ('Subject', models.CharField(max_length=50)),
                ('Message', models.CharField(max_length=300)),
            ],
        ),
    ]
